- name: Prepare the config file
  hosts: localhost
  connection: local
  vars:
    port: "9000"
  tasks:
    - name: Creates directory for configuration file
      file:
        path: ../_build/config
        state: directory
        
    - name: Prepare configuration file
      template:
        src: "./templates/server.config.j2"
        dest: "../_build/config/server.config"
    